// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgclaqjyuokgxgaepzix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnY2xhcWp5dW9rZ3hnYWVweml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjIzNjMsImV4cCI6MjA2OTQ5ODM2M30.ER7l5lv_xBaDz9V_PQzLpA8VI9TK1S93rxHfrswdHPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});